// <auto-generated />
namespace Doanweb1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Addidentity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addidentity));
        
        string IMigrationMetadata.Id
        {
            get { return "202303250858398_Add-identity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
